In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA

In [6]:
data = np.array([[3,4],[2,8],[6,9]])

size = pd.DataFrame(data, columns=["height","width"])
size

height  width
0       3      4
1       2      8
2       6      9

In [18]:
data_mean = np.mean(data.T, axis=1)
size_centered = data - data_mean
size_centered

array([[-0.66666667, -3.        ],
       [-1.66666667,  1.        ],
       [ 2.33333333,  2.        ]])

In [20]:
cov_matrix = np.cov(size_centered.T)
cov_matrix

array([[4.33333333, 2.5       ],
       [2.5       , 7.        ]])

In [23]:
eig_val, eig_vec = np.linalg.eig(cov_matrix)
print(eig_val)
print(eig_vec)

[2.83333333 8.5       ]
[[-0.85749293 -0.51449576]
 [ 0.51449576 -0.85749293]]


In [25]:
projected_data = eig_vec.T.dot(size_centered.T)
projected_data.T

array([[-9.71825316e-01,  2.91547595e+00],
       [ 1.94365063e+00,  1.11022302e-16],
       [-9.71825316e-01, -2.91547595e+00]])

In [27]:
pca = PCA(n_components=2)
pca.fit_transform(size)

array([[ 2.91547595e+00, -9.71825316e-01],
       [-7.37588530e-16,  1.94365063e+00],
       [-2.91547595e+00, -9.71825316e-01]])